apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: humidity-prediction
spec:
  destination:
    name: ''
    namespace: user-akhairaldin
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment
    repoURL: 'https://github.com/zakarya-elmimouni/application-deployment.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true