apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
generateName: humidity-training-workflow-
namespace: user-akhairaldin
spec:
entrypoint: main
serviceAccountName: workflow
arguments:
    parameters:
    # The MLflow tracking server is responsible to log the hyper-parameter and model metrics.
    - name: mlflow-tracking-uri
1        value: https://user-akhairaldin-mlflow.user.lab.sspcloud.fr/
    - name: mlflow-experiment-name
2        value: humidity-prediction
    - name: model-training-conf-list
        value: |
        [
            { "cv": 3 },
            { "cv": 4 },
            { "cv": 5 },
        ]
templates:
    # Entrypoint DAG template
    - name: main
    dag:
        tasks:
        # Task 0: Start pipeline
        - name: start-pipeline
            template: start-pipeline-wt
        # Task 1: Train model with given params
        - name: train-model-with-params
            dependencies: [ start-pipeline ]
            template: run-model-training-wt
            arguments:
            parameters:
                - name: max_features
                value: "{{item.max_features}}"
                - name: n_trees
                value: "{{item.n_trees}}"
            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.model-training-conf-list}}"
    # Now task container templates are defined
    # Worker template for task 0 : start-pipeline
    - name: start-pipeline-wt
    inputs:
    container:
        image: busybox
        command: [ sh, -c ]
        args: [ "echo Starting pipeline" ]
    # Worker template for task-1 : train model with params
    - name: run-model-training-wt
    inputs:
        parameters:
        - name: n_trees
        - name: max_features
    container:
3        image: ahmedkhairaldin/humidity_prediction:new
        imagePullPolicy: Always
        command: [sh, -c]
        args: [
        "python3 train.py --cv={{inputs.parameters.cv}}"
        ]
        env:
        - name: MLFLOW_TRACKING_URI
            value: "{{workflow.parameters.mlflow-tracking-uri}}"
        - name: MLFLOW_EXPERIMENT_NAME
            value: "{{workflow.parameters.mlflow-experiment-name}}"
        - name: AWS_DEFAULT_REGION
            value: us-east-1
        - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr