apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: humidity-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - humidity-prediction.lab.sspcloud.fr
  rules:
    - host: humidity-prediction.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: humidity-service
                port:
                  number: 80
